import type { DocumentSchemaInput } from './types'
import { describe, expect, it } from 'vitest'
import { createDefaultSchema, normalizeDocumentSchema } from './defaults'

// @ts-expect-error version is generated by the schema package, not accepted from host input.
const inputRejectsVersion: DocumentSchemaInput = { version: '0.0.0' }
void inputRejectsVersion

describe('createDefaultSchema', () => {
  it('returns a schema with the current version', () => {
    const schema = createDefaultSchema()
    expect(schema.version).toBe('1.0.0')
  })

  it('uses mm as the default unit', () => {
    const schema = createDefaultSchema()
    expect(schema.unit).toBe('mm')
  })

  it('has page mode fixed', () => {
    const schema = createDefaultSchema()
    expect(schema.page.mode).toBe('fixed')
    expect(schema.page.pageModel?.kind).toBe('paged-paper')
    expect(schema.page.layout?.strategy).toBe('absolute')
    expect(schema.page.pagination?.strategy).toBe('fixed-sheets')
    expect(schema.page.reflow?.strategy).toBe('measure-only')
  })

  it('has A4 dimensions (210x297)', () => {
    const schema = createDefaultSchema()
    expect(schema.page.width).toBe(210)
    expect(schema.page.height).toBe(297)
  })

  it('has empty guides', () => {
    const schema = createDefaultSchema()
    expect(schema.guides).toEqual({ x: [], y: [] })
  })

  it('has empty elements array', () => {
    const schema = createDefaultSchema()
    expect(schema.elements).toEqual([])
  })
})

describe('normalizeDocumentSchema', () => {
  it('returns a default schema for an empty input object', () => {
    const schema = normalizeDocumentSchema({})

    expect(schema).toMatchObject(createDefaultSchema())
  })

  it('uses the current schema version instead of accepting input version', () => {
    const schema = normalizeDocumentSchema({
      version: '0.5.0',
      unit: 'pt',
    } as never)

    expect(schema.version).toBe('1.0.0')
    expect(schema.unit).toBe('pt')
  })

  it('normalizes valid schema with structured page layers', () => {
    const schema = createDefaultSchema()

    expect(normalizeDocumentSchema(schema)).toMatchObject({
      page: {
        mode: 'fixed',
        pageModel: { kind: 'paged-paper' },
        layout: { strategy: 'absolute' },
        pagination: { strategy: 'fixed-sheets' },
        reflow: { strategy: 'measure-only' },
      },
    })
  })

  it('fills missing document, page, and guide fields without discarding valid input', () => {
    const schema = normalizeDocumentSchema({
      unit: 'px',
      page: { width: 80 },
      guides: { x: [10] },
    })

    expect(schema.unit).toBe('px')
    expect(schema.page).toMatchObject({ mode: 'fixed', width: 80, height: 297 })
    expect(schema.guides).toEqual({ x: [10], y: [] })
    expect(schema.elements).toEqual([])
  })

  it('falls back required fields with invalid values', () => {
    const schema = normalizeDocumentSchema({
      unit: 'cm' as never,
      page: { mode: 'book' as never, width: 0, height: -1 },
      guides: { x: 'bad' as never, y: [20] },
      elements: 'bad' as never,
    })

    expect(schema.unit).toBe('mm')
    expect(schema.page).toMatchObject({ mode: 'fixed', width: 210, height: 297 })
    expect(schema.guides).toEqual({ x: [], y: [20] })
    expect(schema.elements).toEqual([])
  })

  it('derives continuous-paper layers from continuous mode', () => {
    const continuous = normalizeDocumentSchema({ page: { mode: 'continuous', width: 80, height: 200 } })

    expect(continuous.page.pageModel?.kind).toBe('continuous-paper')
    expect(continuous.page.layout).toMatchObject({ strategy: 'stack-flow', flowAxis: 'y' })
    expect(continuous.page.pagination?.strategy).toBe('none')
    expect(continuous.page.reflow).toMatchObject({ strategy: 'flow-y', preserveTrailingGap: true })
  })

  it('treats unknown mode as invalid loose input and falls back to fixed mode', () => {
    const schema = normalizeDocumentSchema({
      page: {
        mode: 'book',
        width: 80,
        height: 200,
      },
    } as never)

    expect(schema.page).toMatchObject({
      mode: 'fixed',
      pageModel: { kind: 'paged-paper', paper: { width: 80, height: 200 } },
      layout: { strategy: 'absolute' },
      pagination: { strategy: 'fixed-sheets' },
      reflow: { strategy: 'measure-only' },
    })
  })

  it('preserves explicit structured strategies while filling missing parts', () => {
    const schema = normalizeDocumentSchema({
      page: {
        mode: 'fixed',
        width: 80,
        height: 120,
        layout: { strategy: 'stack-flow' },
        pagination: { strategy: 'auto-sheets', pageCount: 3 },
      },
    })

    expect(schema.page.pageModel).toMatchObject({ kind: 'paged-paper', paper: { width: 80, height: 120 } })
    expect(schema.page.layout).toMatchObject({ strategy: 'stack-flow' })
    expect(schema.page.pagination).toMatchObject({ strategy: 'auto-sheets', pageCount: 3 })
    expect(schema.page.reflow?.strategy).toBe('measure-only')
  })

  it('normalizes text watermark page layer settings', () => {
    const schema = normalizeDocumentSchema({
      page: {
        layers: [
          {
            id: '',
            kind: 'watermark',
            type: 'text',
            enabled: true,
            placement: 'top',
            zIndex: 2000,
            text: 'CONFIDENTIAL',
            rotation: Number.NaN,
            opacity: 2,
            fontSize: 0,
            gap: 20,
            color: '',
          },
        ],
      },
    })

    expect(schema.page.layers).toEqual([
      {
        id: 'page-watermark',
        kind: 'watermark',
        type: 'text',
        enabled: true,
        placement: 'top',
        zIndex: 999,
        text: 'CONFIDENTIAL',
        rotation: -30,
        opacity: 1,
        fontSize: 18,
        gap: 20,
        color: '#b8b8b8',
      },
    ])
  })

  it('drops unsupported page layers from loose input', () => {
    const schema = normalizeDocumentSchema({
      page: {
        layers: [
          { id: 'image-watermark', kind: 'watermark', type: 'image', enabled: true },
          { id: 'unknown', kind: 'unknown', enabled: true },
        ],
      },
    } as never)

    expect(schema.page.layers).toBeUndefined()
  })

  it('drops unsupported page fields from loose input', () => {
    const schema = normalizeDocumentSchema({
      page: {
        unsupportedRenderConfig: { enabled: true },
      },
    } as never)

    expect('unsupportedRenderConfig' in schema.page).toBe(false)
    expect(schema.page.layers).toBeUndefined()
  })
})
