import type { BuiltinDesignerMaterialBundle, BuiltinPanelSectionId } from './types'
import {
  IconBarcode,
  IconChartBar,
  IconChartCustom,
  IconChartGauge,
  IconChartLine,
  IconChartPie,
  IconChartRadar,
  IconChartScatter,
  IconDataTable,
  IconEllipse,
  IconHeart,
  IconImage,
  IconLayoutPanelTop,
  IconLine,
  IconPageNumber,
  IconQrcode,
  IconRect,
  IconStar,
  IconSvg,
  IconTable,
  IconText,
} from '@easyink/icons'
import {
  BARCODE_CAPABILITIES,
  BARCODE_TYPE,
  barcodeAIMaterialDescriptor,
  barcodeDesignerPropSchemas,
  barcodeLocaleMessages,
  createBarcodeExtension,
  createBarcodeNode,
} from '@easyink/material-barcode'
import {
  CHART_BAR_CAPABILITIES,
  CHART_BAR_TYPE,
  chartBarAIMaterialDescriptor,
  chartBarDesignerPropSchemas,
  chartBarLocaleMessages,
  createChartBarExtension,
  createChartBarNode,
} from '@easyink/material-chart-bar'
import { chartCustomAIMaterialDescriptor } from '@easyink/material-chart-custom/ai'
import { chartCustomLocaleMessages } from '@easyink/material-chart-custom/locale'
import { chartCustomDesignerPropSchemas } from '@easyink/material-chart-custom/prop-schemas'
import {
  CHART_CUSTOM_CAPABILITIES,
  CHART_CUSTOM_TYPE,
  createChartCustomNode,
} from '@easyink/material-chart-custom/schema'
import {
  CHART_GAUGE_CAPABILITIES,
  CHART_GAUGE_TYPE,
  chartGaugeAIMaterialDescriptor,
  chartGaugeDesignerPropSchemas,
  chartGaugeLocaleMessages,
  createChartGaugeExtension,
  createChartGaugeNode,
} from '@easyink/material-chart-gauge'
import {
  CHART_LINE_CAPABILITIES,
  CHART_LINE_TYPE,
  chartLineAIMaterialDescriptor,
  chartLineDesignerPropSchemas,
  chartLineLocaleMessages,
  createChartLineExtension,
  createChartLineNode,
} from '@easyink/material-chart-line'
import {
  CHART_PIE_CAPABILITIES,
  CHART_PIE_TYPE,
  chartPieAIMaterialDescriptor,
  chartPieDesignerPropSchemas,
  chartPieLocaleMessages,
  createChartPieExtension,
  createChartPieNode,
} from '@easyink/material-chart-pie'
import {
  CHART_RADAR_CAPABILITIES,
  CHART_RADAR_TYPE,
  chartRadarAIMaterialDescriptor,
  chartRadarDesignerPropSchemas,
  chartRadarLocaleMessages,
  createChartRadarExtension,
  createChartRadarNode,
} from '@easyink/material-chart-radar'
import {
  CHART_SCATTER_CAPABILITIES,
  CHART_SCATTER_TYPE,
  chartScatterAIMaterialDescriptor,
  chartScatterDesignerPropSchemas,
  chartScatterLocaleMessages,
  createChartScatterExtension,
  createChartScatterNode,
} from '@easyink/material-chart-scatter'
import {
  createEllipseExtension,
  createEllipseNode,
  ELLIPSE_CAPABILITIES,
  ELLIPSE_TYPE,
  ellipseAIMaterialDescriptor,
  ellipseDesignerPropSchemas,
  ellipseLocaleMessages,
} from '@easyink/material-ellipse'
import {
  createFlowRowExtension,
  createFlowRowNode,
  FLOW_ROW_CAPABILITIES,
  FLOW_ROW_TYPE,
  flowRowAIMaterialDescriptor,
  flowRowDesignerPropSchemas,
  flowRowLocaleMessages,
} from '@easyink/material-flow-row'
import {
  createImageExtension,
  createImageNode,
  IMAGE_CAPABILITIES,
  IMAGE_TYPE,
  imageAIMaterialDescriptor,
  imageDesignerPropSchemas,
  imageLocaleMessages,
} from '@easyink/material-image'
import {
  createLineExtension,
  createLineNode,
  LINE_CAPABILITIES,
  LINE_TYPE,
  lineAIMaterialDescriptor,
  lineDesignerPropSchemas,
  lineLocaleMessages,
} from '@easyink/material-line'
import {
  createPageNumberExtension,
  createPageNumberNode,
  PAGE_NUMBER_CAPABILITIES,
  PAGE_NUMBER_TYPE,
  pageNumberAIMaterialDescriptor,
  pageNumberDesignerPropSchemas,
  pageNumberLocaleMessages,
} from '@easyink/material-page-number'
import {
  createQrcodeExtension,
  createQrcodeNode,
  QRCODE_CAPABILITIES,
  QRCODE_TYPE,
  qrcodeAIMaterialDescriptor,
  qrcodeDesignerPropSchemas,
  qrcodeLocaleMessages,
} from '@easyink/material-qrcode'
import {
  createRectExtension,
  createRectNode,
  RECT_CAPABILITIES,
  RECT_TYPE,
  rectAIMaterialDescriptor,
  rectDesignerPropSchemas,
  rectLocaleMessages,
} from '@easyink/material-rect'
import {
  createSvgCustomExtension,
  createSvgCustomNode,
  SVG_CUSTOM_CAPABILITIES,
  SVG_CUSTOM_TYPE,
  svgCustomAIMaterialDescriptor,
  svgCustomDesignerPropSchemas,
  svgCustomLocaleMessages,
} from '@easyink/material-svg-custom'
import {
  createSvgHeartExtension,
  createSvgHeartNode,
  SVG_HEART_CAPABILITIES,
  SVG_HEART_TYPE,
  svgHeartAIMaterialDescriptor,
  svgHeartDesignerPropSchemas,
  svgHeartLocaleMessages,
} from '@easyink/material-svg-heart'
import {
  createSvgStarExtension,
  createSvgStarNode,
  SVG_STAR_CAPABILITIES,
  SVG_STAR_TYPE,
  svgStarAIMaterialDescriptor,
  svgStarDesignerPropSchemas,
  svgStarLocaleMessages,
} from '@easyink/material-svg-star'
import {
  createTableDataExtension,
  createTableDataNode,
  TABLE_DATA_CAPABILITIES,
  TABLE_DATA_TYPE,
  tableDataAIMaterialDescriptor,
  tableDataDesignerPropSchemas,
  tableDataLocaleMessages,
} from '@easyink/material-table-data'
import { tableKernelLocaleMessages } from '@easyink/material-table-kernel'
import {
  createTableStaticExtension,
  createTableStaticNode,
  TABLE_STATIC_CAPABILITIES,
  TABLE_STATIC_TYPE,
  tableStaticAIMaterialDescriptor,
  tableStaticDesignerPropSchemas,
  tableStaticLocaleMessages,
} from '@easyink/material-table-static'
import {
  createTextExtension,
  createTextNode,
  TEXT_CAPABILITIES,
  TEXT_TYPE,
  textAIMaterialDescriptor,
  textDesignerPropSchemas,
  textLocaleMessages,
} from '@easyink/material-text'
import {
  barcodeMaterialBinding,
  chartBarMaterialBinding,
  chartCustomMaterialBinding,
  chartGaugeMaterialBinding,
  chartLineMaterialBinding,
  chartPieMaterialBinding,
  chartRadarMaterialBinding,
  chartScatterMaterialBinding,
  customMaterialBinding,
  imageMaterialBinding,
  noMaterialBinding,
  qrcodeMaterialBinding,
  svgCustomMaterialBinding,
  textMaterialBinding,
} from './bindings'

function tableSectionFilter(sectionId: BuiltinPanelSectionId): boolean {
  return sectionId !== 'binding'
}

export const builtinDesignerMaterialBundle: BuiltinDesignerMaterialBundle = {
  localeMessages: tableKernelLocaleMessages,
  materials: [
    {
      type: TEXT_TYPE,
      name: 'materials.text.name',
      icon: IconText,
      category: 'basic',
      capabilities: TEXT_CAPABILITIES,
      binding: textMaterialBinding,
      aiDescriptor: textAIMaterialDescriptor,
      createDefaultNode: createTextNode,
      factory: createTextExtension,
      propSchemas: textDesignerPropSchemas,
      localeMessages: textLocaleMessages,
    },
    {
      type: IMAGE_TYPE,
      name: 'materials.image.name',
      icon: IconImage,
      category: 'basic',
      capabilities: IMAGE_CAPABILITIES,
      binding: imageMaterialBinding,
      aiDescriptor: imageAIMaterialDescriptor,
      createDefaultNode: createImageNode,
      factory: createImageExtension,
      propSchemas: imageDesignerPropSchemas,
      localeMessages: imageLocaleMessages,
    },
    {
      type: BARCODE_TYPE,
      name: 'materials.barcode.name',
      icon: IconBarcode,
      category: 'basic',
      capabilities: BARCODE_CAPABILITIES,
      binding: barcodeMaterialBinding,
      aiDescriptor: barcodeAIMaterialDescriptor,
      createDefaultNode: createBarcodeNode,
      factory: createBarcodeExtension,
      propSchemas: barcodeDesignerPropSchemas,
      localeMessages: barcodeLocaleMessages,
    },
    {
      type: QRCODE_TYPE,
      name: 'materials.qrcode.name',
      icon: IconQrcode,
      category: 'basic',
      capabilities: QRCODE_CAPABILITIES,
      binding: qrcodeMaterialBinding,
      aiDescriptor: qrcodeAIMaterialDescriptor,
      createDefaultNode: createQrcodeNode,
      factory: createQrcodeExtension,
      propSchemas: qrcodeDesignerPropSchemas,
      localeMessages: qrcodeLocaleMessages,
    },
    {
      type: LINE_TYPE,
      name: 'materials.line.name',
      icon: IconLine,
      category: 'basic',
      capabilities: LINE_CAPABILITIES,
      binding: noMaterialBinding,
      aiDescriptor: lineAIMaterialDescriptor,
      createDefaultNode: createLineNode,
      factory: createLineExtension,
      propSchemas: lineDesignerPropSchemas,
      localeMessages: lineLocaleMessages,
    },
    {
      type: RECT_TYPE,
      name: 'materials.rect.name',
      icon: IconRect,
      category: 'basic',
      capabilities: RECT_CAPABILITIES,
      binding: noMaterialBinding,
      aiDescriptor: rectAIMaterialDescriptor,
      createDefaultNode: createRectNode,
      factory: createRectExtension,
      propSchemas: rectDesignerPropSchemas,
      localeMessages: rectLocaleMessages,
    },
    {
      type: ELLIPSE_TYPE,
      name: 'materials.ellipse.name',
      icon: IconEllipse,
      category: 'basic',
      capabilities: ELLIPSE_CAPABILITIES,
      binding: noMaterialBinding,
      aiDescriptor: ellipseAIMaterialDescriptor,
      createDefaultNode: createEllipseNode,
      factory: createEllipseExtension,
      propSchemas: ellipseDesignerPropSchemas,
      localeMessages: ellipseLocaleMessages,
    },
    {
      type: TABLE_STATIC_TYPE,
      name: 'materials.tableStatic.name',
      icon: IconTable,
      category: 'data',
      capabilities: TABLE_STATIC_CAPABILITIES,
      binding: customMaterialBinding,
      aiDescriptor: tableStaticAIMaterialDescriptor,
      createDefaultNode: createTableStaticNode,
      factory: createTableStaticExtension,
      propSchemas: tableStaticDesignerPropSchemas,
      localeMessages: tableStaticLocaleMessages,
      sectionFilter: tableSectionFilter,
    },
    {
      type: TABLE_DATA_TYPE,
      name: 'materials.tableData.name',
      icon: IconDataTable,
      category: 'data',
      capabilities: TABLE_DATA_CAPABILITIES,
      binding: customMaterialBinding,
      aiDescriptor: tableDataAIMaterialDescriptor,
      createDefaultNode: createTableDataNode,
      factory: createTableDataExtension,
      propSchemas: tableDataDesignerPropSchemas,
      localeMessages: tableDataLocaleMessages,
      sectionFilter: tableSectionFilter,
    },
    {
      type: FLOW_ROW_TYPE,
      name: 'materials.flowRow.name',
      icon: IconLayoutPanelTop,
      category: 'data',
      capabilities: FLOW_ROW_CAPABILITIES,
      binding: customMaterialBinding,
      aiDescriptor: flowRowAIMaterialDescriptor,
      createDefaultNode: createFlowRowNode,
      factory: createFlowRowExtension,
      propSchemas: flowRowDesignerPropSchemas,
      localeMessages: flowRowLocaleMessages,
    },
    {
      type: CHART_BAR_TYPE,
      name: 'materials.chartBar.name',
      icon: IconChartBar,
      category: 'chart',
      capabilities: CHART_BAR_CAPABILITIES,
      binding: chartBarMaterialBinding,
      aiDescriptor: chartBarAIMaterialDescriptor,
      createDefaultNode: createChartBarNode,
      factory: createChartBarExtension,
      propSchemas: chartBarDesignerPropSchemas,
      localeMessages: chartBarLocaleMessages,
    },
    {
      type: CHART_LINE_TYPE,
      name: 'materials.chartLine.name',
      icon: IconChartLine,
      category: 'chart',
      capabilities: CHART_LINE_CAPABILITIES,
      binding: chartLineMaterialBinding,
      aiDescriptor: chartLineAIMaterialDescriptor,
      createDefaultNode: createChartLineNode,
      factory: createChartLineExtension,
      propSchemas: chartLineDesignerPropSchemas,
      localeMessages: chartLineLocaleMessages,
    },
    {
      type: CHART_PIE_TYPE,
      name: 'materials.chartPie.name',
      icon: IconChartPie,
      category: 'chart',
      capabilities: CHART_PIE_CAPABILITIES,
      binding: chartPieMaterialBinding,
      aiDescriptor: chartPieAIMaterialDescriptor,
      createDefaultNode: createChartPieNode,
      factory: createChartPieExtension,
      propSchemas: chartPieDesignerPropSchemas,
      localeMessages: chartPieLocaleMessages,
    },
    {
      type: CHART_RADAR_TYPE,
      name: 'materials.chartRadar.name',
      icon: IconChartRadar,
      category: 'chart',
      capabilities: CHART_RADAR_CAPABILITIES,
      binding: chartRadarMaterialBinding,
      aiDescriptor: chartRadarAIMaterialDescriptor,
      createDefaultNode: createChartRadarNode,
      factory: createChartRadarExtension,
      propSchemas: chartRadarDesignerPropSchemas,
      localeMessages: chartRadarLocaleMessages,
    },
    {
      type: CHART_SCATTER_TYPE,
      name: 'materials.chartScatter.name',
      icon: IconChartScatter,
      category: 'chart',
      capabilities: CHART_SCATTER_CAPABILITIES,
      binding: chartScatterMaterialBinding,
      aiDescriptor: chartScatterAIMaterialDescriptor,
      createDefaultNode: createChartScatterNode,
      factory: createChartScatterExtension,
      propSchemas: chartScatterDesignerPropSchemas,
      localeMessages: chartScatterLocaleMessages,
    },
    {
      type: CHART_GAUGE_TYPE,
      name: 'materials.chartGauge.name',
      icon: IconChartGauge,
      category: 'chart',
      capabilities: CHART_GAUGE_CAPABILITIES,
      binding: chartGaugeMaterialBinding,
      aiDescriptor: chartGaugeAIMaterialDescriptor,
      createDefaultNode: createChartGaugeNode,
      factory: createChartGaugeExtension,
      propSchemas: chartGaugeDesignerPropSchemas,
      localeMessages: chartGaugeLocaleMessages,
    },
    {
      type: CHART_CUSTOM_TYPE,
      name: 'materials.chartCustom.name',
      icon: IconChartCustom,
      category: 'chart',
      capabilities: CHART_CUSTOM_CAPABILITIES,
      binding: chartCustomMaterialBinding,
      aiDescriptor: chartCustomAIMaterialDescriptor,
      createDefaultNode: createChartCustomNode,
      factory: () => ({ renderContent: () => () => {} }),
      lazyFactory: async () => (await import('@easyink/material-chart-custom/designer')).createChartCustomExtension,
      propSchemas: chartCustomDesignerPropSchemas,
      localeMessages: chartCustomLocaleMessages,
    },
    {
      type: SVG_CUSTOM_TYPE,
      name: 'materials.svgCustom.name',
      icon: IconSvg,
      category: 'svg',
      capabilities: SVG_CUSTOM_CAPABILITIES,
      binding: svgCustomMaterialBinding,
      aiDescriptor: svgCustomAIMaterialDescriptor,
      createDefaultNode: createSvgCustomNode,
      factory: createSvgCustomExtension,
      propSchemas: svgCustomDesignerPropSchemas,
      localeMessages: svgCustomLocaleMessages,
    },
    {
      type: SVG_STAR_TYPE,
      name: 'materials.svgStar.name',
      icon: IconStar,
      category: 'svg',
      capabilities: SVG_STAR_CAPABILITIES,
      binding: noMaterialBinding,
      aiDescriptor: svgStarAIMaterialDescriptor,
      createDefaultNode: createSvgStarNode,
      factory: createSvgStarExtension,
      propSchemas: svgStarDesignerPropSchemas,
      localeMessages: svgStarLocaleMessages,
    },
    {
      type: SVG_HEART_TYPE,
      name: 'materials.svgHeart.name',
      icon: IconHeart,
      category: 'svg',
      capabilities: SVG_HEART_CAPABILITIES,
      binding: noMaterialBinding,
      aiDescriptor: svgHeartAIMaterialDescriptor,
      createDefaultNode: createSvgHeartNode,
      factory: createSvgHeartExtension,
      propSchemas: svgHeartDesignerPropSchemas,
      localeMessages: svgHeartLocaleMessages,
    },
    {
      type: PAGE_NUMBER_TYPE,
      name: 'materials.pageNumber.name',
      icon: IconPageNumber,
      category: 'utility',
      capabilities: PAGE_NUMBER_CAPABILITIES,
      binding: noMaterialBinding,
      aiDescriptor: pageNumberAIMaterialDescriptor,
      createDefaultNode: createPageNumberNode,
      factory: createPageNumberExtension,
      propSchemas: pageNumberDesignerPropSchemas,
      localeMessages: pageNumberLocaleMessages,
    },
  ],
  quickMaterialTypes: [
    LINE_TYPE,
    RECT_TYPE,
    ELLIPSE_TYPE,
    TEXT_TYPE,
    IMAGE_TYPE,
    QRCODE_TYPE,
    BARCODE_TYPE,
  ],
  groupedCatalog: [
    { type: TABLE_STATIC_TYPE, group: 'data' },
    { type: TABLE_DATA_TYPE, group: 'data' },
    { type: FLOW_ROW_TYPE, group: 'data' },
    { type: CHART_BAR_TYPE, group: 'chart' },
    { type: CHART_LINE_TYPE, group: 'chart' },
    { type: CHART_PIE_TYPE, group: 'chart' },
    { type: CHART_RADAR_TYPE, group: 'chart' },
    { type: CHART_SCATTER_TYPE, group: 'chart' },
    { type: CHART_GAUGE_TYPE, group: 'chart' },
    { type: CHART_CUSTOM_TYPE, group: 'chart' },
    { type: SVG_STAR_TYPE, group: 'svg' },
    { type: SVG_HEART_TYPE, group: 'svg' },
    { type: SVG_CUSTOM_TYPE, group: 'svg' },
    { type: PAGE_NUMBER_TYPE, group: 'utility' },
  ],
}
