import type { BuiltinDesignerMaterialBundle, BuiltinPanelSectionId } from './types'
import {
  IconBarcode,
  IconChart,
  IconDataTable,
  IconEllipse,
  IconHeart,
  IconImage,
  IconLayoutPanelTop,
  IconLine,
  IconPageNumber,
  IconQrcode,
  IconRect,
  IconStar,
  IconSvg,
  IconTable,
  IconText,
} from '@easyink/icons'
import {
  BARCODE_CAPABILITIES,
  BARCODE_TYPE,
  barcodeAIMaterialDescriptor,
  createBarcodeExtension,
  createBarcodeNode,
} from '@easyink/material-barcode'
import {
  CHART_BAR_CAPABILITIES,
  CHART_BAR_TYPE,
  chartBarAIMaterialDescriptor,
  chartBarDesignerPropSchemas,
  createChartBarExtension,
  createChartBarNode,
} from '@easyink/material-chart-bar'
import {
  createEllipseExtension,
  createEllipseNode,
  ELLIPSE_CAPABILITIES,
  ELLIPSE_TYPE,
  ellipseAIMaterialDescriptor,
} from '@easyink/material-ellipse'
import {
  createFlowRowExtension,
  createFlowRowNode,
  FLOW_ROW_CAPABILITIES,
  FLOW_ROW_TYPE,
  flowRowAIMaterialDescriptor,
} from '@easyink/material-flow-row'
import {
  createImageExtension,
  createImageNode,
  IMAGE_CAPABILITIES,
  IMAGE_TYPE,
  imageAIMaterialDescriptor,
} from '@easyink/material-image'
import {
  createLineExtension,
  createLineNode,
  LINE_CAPABILITIES,
  LINE_TYPE,
  lineAIMaterialDescriptor,
} from '@easyink/material-line'
import {
  createPageNumberExtension,
  createPageNumberNode,
  PAGE_NUMBER_CAPABILITIES,
  PAGE_NUMBER_TYPE,
  pageNumberAIMaterialDescriptor,
} from '@easyink/material-page-number'
import {
  createQrcodeExtension,
  createQrcodeNode,
  QRCODE_CAPABILITIES,
  QRCODE_TYPE,
  qrcodeAIMaterialDescriptor,
} from '@easyink/material-qrcode'
import {
  createRectExtension,
  createRectNode,
  RECT_CAPABILITIES,
  RECT_TYPE,
  rectAIMaterialDescriptor,
} from '@easyink/material-rect'
import {
  createSvgCustomExtension,
  createSvgCustomNode,
  SVG_CUSTOM_CAPABILITIES,
  SVG_CUSTOM_TYPE,
  svgCustomAIMaterialDescriptor,
  svgCustomDesignerPropSchemas,
} from '@easyink/material-svg-custom'
import {
  createSvgHeartExtension,
  createSvgHeartNode,
  SVG_HEART_CAPABILITIES,
  SVG_HEART_TYPE,
  svgHeartAIMaterialDescriptor,
  svgHeartDesignerPropSchemas,
} from '@easyink/material-svg-heart'
import {
  createSvgStarExtension,
  createSvgStarNode,
  SVG_STAR_CAPABILITIES,
  SVG_STAR_TYPE,
  svgStarAIMaterialDescriptor,
  svgStarDesignerPropSchemas,
} from '@easyink/material-svg-star'
import {
  createTableDataExtension,
  createTableDataNode,
  TABLE_DATA_CAPABILITIES,
  TABLE_DATA_TYPE,
  tableDataAIMaterialDescriptor,
  tableDataDesignerPropSchemas,
} from '@easyink/material-table-data'
import {
  createTableStaticExtension,
  createTableStaticNode,
  TABLE_STATIC_CAPABILITIES,
  TABLE_STATIC_TYPE,
  tableStaticAIMaterialDescriptor,
} from '@easyink/material-table-static'
import {
  createTextExtension,
  createTextNode,
  TEXT_CAPABILITIES,
  TEXT_TYPE,
  textAIMaterialDescriptor,
} from '@easyink/material-text'

function tableSectionFilter(sectionId: BuiltinPanelSectionId): boolean {
  return sectionId !== 'binding'
}

export const builtinDesignerMaterialBundle: BuiltinDesignerMaterialBundle = {
  materials: [
    {
      type: TEXT_TYPE,
      name: 'designer.toolbar.text',
      icon: IconText,
      category: 'basic',
      capabilities: TEXT_CAPABILITIES,
      aiDescriptor: textAIMaterialDescriptor,
      createDefaultNode: createTextNode,
      factory: createTextExtension,
    },
    {
      type: IMAGE_TYPE,
      name: 'designer.toolbar.image',
      icon: IconImage,
      category: 'basic',
      capabilities: IMAGE_CAPABILITIES,
      aiDescriptor: imageAIMaterialDescriptor,
      createDefaultNode: createImageNode,
      factory: createImageExtension,
    },
    {
      type: BARCODE_TYPE,
      name: 'designer.toolbar.barcode',
      icon: IconBarcode,
      category: 'basic',
      capabilities: BARCODE_CAPABILITIES,
      aiDescriptor: barcodeAIMaterialDescriptor,
      createDefaultNode: createBarcodeNode,
      factory: createBarcodeExtension,
    },
    {
      type: QRCODE_TYPE,
      name: 'designer.toolbar.qrcode',
      icon: IconQrcode,
      category: 'basic',
      capabilities: QRCODE_CAPABILITIES,
      aiDescriptor: qrcodeAIMaterialDescriptor,
      createDefaultNode: createQrcodeNode,
      factory: createQrcodeExtension,
    },
    {
      type: LINE_TYPE,
      name: 'designer.toolbar.line',
      icon: IconLine,
      category: 'basic',
      capabilities: LINE_CAPABILITIES,
      aiDescriptor: lineAIMaterialDescriptor,
      createDefaultNode: createLineNode,
      factory: createLineExtension,
    },
    {
      type: RECT_TYPE,
      name: 'designer.toolbar.rect',
      icon: IconRect,
      category: 'basic',
      capabilities: RECT_CAPABILITIES,
      aiDescriptor: rectAIMaterialDescriptor,
      createDefaultNode: createRectNode,
      factory: createRectExtension,
    },
    {
      type: ELLIPSE_TYPE,
      name: 'designer.toolbar.ellipse',
      icon: IconEllipse,
      category: 'basic',
      capabilities: ELLIPSE_CAPABILITIES,
      aiDescriptor: ellipseAIMaterialDescriptor,
      createDefaultNode: createEllipseNode,
      factory: createEllipseExtension,
    },
    {
      type: TABLE_STATIC_TYPE,
      name: 'designer.toolbar.table',
      icon: IconTable,
      category: 'data',
      capabilities: TABLE_STATIC_CAPABILITIES,
      aiDescriptor: tableStaticAIMaterialDescriptor,
      createDefaultNode: createTableStaticNode,
      factory: createTableStaticExtension,
      sectionFilter: tableSectionFilter,
    },
    {
      type: TABLE_DATA_TYPE,
      name: 'designer.toolbar.dataTable',
      icon: IconDataTable,
      category: 'data',
      capabilities: TABLE_DATA_CAPABILITIES,
      aiDescriptor: tableDataAIMaterialDescriptor,
      createDefaultNode: createTableDataNode,
      factory: createTableDataExtension,
      propSchemas: tableDataDesignerPropSchemas,
      sectionFilter: tableSectionFilter,
    },
    {
      type: FLOW_ROW_TYPE,
      name: 'designer.toolbar.flowRow',
      icon: IconLayoutPanelTop,
      category: 'data',
      capabilities: FLOW_ROW_CAPABILITIES,
      aiDescriptor: flowRowAIMaterialDescriptor,
      createDefaultNode: createFlowRowNode,
      factory: createFlowRowExtension,
    },
    {
      type: CHART_BAR_TYPE,
      name: 'designer.toolbar.chartBar',
      icon: IconChart,
      category: 'chart',
      capabilities: CHART_BAR_CAPABILITIES,
      aiDescriptor: chartBarAIMaterialDescriptor,
      createDefaultNode: createChartBarNode,
      factory: createChartBarExtension,
      propSchemas: chartBarDesignerPropSchemas,
    },
    {
      type: SVG_CUSTOM_TYPE,
      name: 'designer.toolbar.svgCustom',
      icon: IconSvg,
      category: 'svg',
      capabilities: SVG_CUSTOM_CAPABILITIES,
      aiDescriptor: svgCustomAIMaterialDescriptor,
      createDefaultNode: createSvgCustomNode,
      factory: createSvgCustomExtension,
      propSchemas: svgCustomDesignerPropSchemas,
    },
    {
      type: SVG_STAR_TYPE,
      name: 'designer.toolbar.svgStar',
      icon: IconStar,
      category: 'svg',
      capabilities: SVG_STAR_CAPABILITIES,
      aiDescriptor: svgStarAIMaterialDescriptor,
      createDefaultNode: createSvgStarNode,
      factory: createSvgStarExtension,
      propSchemas: svgStarDesignerPropSchemas,
    },
    {
      type: SVG_HEART_TYPE,
      name: 'designer.toolbar.svgHeart',
      icon: IconHeart,
      category: 'svg',
      capabilities: SVG_HEART_CAPABILITIES,
      aiDescriptor: svgHeartAIMaterialDescriptor,
      createDefaultNode: createSvgHeartNode,
      factory: createSvgHeartExtension,
      propSchemas: svgHeartDesignerPropSchemas,
    },
    {
      type: PAGE_NUMBER_TYPE,
      name: 'designer.toolbar.pageNumber',
      icon: IconPageNumber,
      category: 'utility',
      capabilities: PAGE_NUMBER_CAPABILITIES,
      aiDescriptor: pageNumberAIMaterialDescriptor,
      createDefaultNode: createPageNumberNode,
      factory: createPageNumberExtension,
    },
  ],
  quickMaterialTypes: [
    LINE_TYPE,
    RECT_TYPE,
    ELLIPSE_TYPE,
    TEXT_TYPE,
    IMAGE_TYPE,
    QRCODE_TYPE,
    BARCODE_TYPE,
  ],
  groupedCatalog: [
    { type: TABLE_STATIC_TYPE, group: 'data' },
    { type: TABLE_DATA_TYPE, group: 'data' },
    { type: FLOW_ROW_TYPE, group: 'data' },
    { type: CHART_BAR_TYPE, group: 'chart' },
    { type: SVG_STAR_TYPE, group: 'svg' },
    { type: SVG_HEART_TYPE, group: 'svg' },
    { type: SVG_CUSTOM_TYPE, group: 'svg' },
    { type: PAGE_NUMBER_TYPE, group: 'utility' },
  ],
}
