import { createIcon } from './createIcon'

export { createIcon } from './createIcon'
export type { CreateIconOptions } from './createIcon'

export const IconRingProgress = createIcon({
  name: 'IconRingProgress',
  svg: '<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4.5"/>',
})

export const IconProgress = createIcon({
  name: 'IconProgress',
  svg: '<rect width="18" height="6" x="3" y="9" rx="3"/><path d="M6 12h7"/>',
})

export {
  AlignEndVertical as IconAlignBottom,
  AlignCenter as IconAlignCenter,
  AlignCenterHorizontal as IconAlignCenterH,
  AlignEndHorizontal as IconAlignEnd,
  AlignLeft as IconAlignLeft,
  AlignCenterVertical as IconAlignMiddle,
  AlignRight as IconAlignRight,
  AlignStartHorizontal as IconAlignStart,
  AlignStartVertical as IconAlignTop,
  Barcode as IconBarcode,
  Bold as IconBold,
  Bot as IconBot,
  Bug as IconBug,
  BarChart3 as IconChart,
  ChartColumn as IconChartBar,
  ChartNoAxesCombined as IconChartCustom,
  Gauge as IconChartGauge,
  ChartLine as IconChartLine,
  ChartPie as IconChartPie,
  Radar as IconChartRadar,
  ChartScatter as IconChartScatter,
  Check as IconCheck,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  CircleAlert as IconCircleAlert,
  CircleDot as IconCircleDot,
  Eraser as IconClear,
  X as IconClose,
  ChevronsUpDown as IconCollapse,
  LayoutGrid as IconContainer,
  Copy as IconCopy,
  CopyPlus as IconCopyPlus,
  Database as IconDatabase,
  Table2 as IconDataTable,
  Trash2 as IconDelete,
  AlignHorizontalSpaceBetween as IconDistribute,
  SeparatorVertical as IconDivider,
  ChevronDown as IconDown,
  SquarePen as IconEdit,
  Circle as IconEllipse,
  ChevronsRightLeft as IconExpand,
  Download as IconExport,
  FileCheck as IconFileCheck,
  FilePen as IconFilePen,
  FileText as IconFileText,
  FlipHorizontal2 as IconFlipHorizontal2,
  FolderClosed as IconFolderClosed,
  FolderOpen as IconFolderOpen,
  Grid3x3 as IconGrid,
  GripVertical as IconGripVertical,
  Group as IconGroup,
  Hash as IconHash,
  Heart as IconHeart,
  EyeOff as IconHidden,
  History as IconHistory,
  Image as IconImage,
  Upload as IconImport,
  Italic as IconItalic,
  ArrowDownToLine as IconLayerBottom,
  ArrowDown as IconLayerDown,
  ArrowUpToLine as IconLayerTop,
  ArrowUp as IconLayerUp,
  LayoutPanelTop as IconLayoutPanelTop,
  Minus as IconLine,
  ListTree as IconListTree,
  Loader as IconLoader,
  Lock as IconLock,
  Settings as IconManager,
  Map as IconMap,
  Maximize2 as IconMaximize,
  MessageSquare as IconMessageSquare,
  Minus as IconMinimize,
  Monitor as IconMonitor,
  FilePlus as IconNewTemplate,
  BookOpen as IconPageNumber,
  PanelLeft as IconPanelLeft,
  Blocks as IconPanelMaterials,
  ClipboardPaste as IconPaste,
  Plus as IconPlus,
  Eye as IconPreview,
  Printer as IconPrint,
  QrCode as IconQrcode,
  Square as IconRect,
  Redo2 as IconRedo,
  RotateCcw as IconRestoreDefault,
  RotateCw as IconRotation,
  Ruler as IconRuler,
  RulerDimensionLine as IconRulerDimensionLine,
  Save as IconSave,
  Scissors as IconScissors,
  ScissorsLineDashed as IconScissorsLineDashed,
  Search as IconSearch,
  SquareDashedMousePointer as IconSelectAll,
  BoxSelect as IconSelectSameType,
  Send as IconSend,
  SlidersHorizontal as IconSliders,
  Magnet as IconSnap,
  Sparkles as IconSparkles,
  Star as IconStar,
  StretchHorizontal as IconStretchHorizontal,
  FileCode as IconSvg,
  Table as IconTable,
  BetweenVerticalStart as IconTableInsertColLeft,
  BetweenVerticalEnd as IconTableInsertColRight,
  BetweenHorizontalStart as IconTableInsertRowAbove,
  BetweenHorizontalEnd as IconTableInsertRowBelow,
  TableCellsMerge as IconTableMerge,
  TableColumnsSplit as IconTableRemoveCol,
  TableRowsSplit as IconTableRemoveRow,
  TableCellsSplit as IconTableSplit,
  Type as IconText,
  AlignCenter as IconTextAlignCenter,
  AlignLeft as IconTextAlignLeft,
  AlignRight as IconTextAlignRight,
  Underline as IconUnderline,
  Undo2 as IconUndo,
  Ungroup as IconUngroup,
  Unlock as IconUnlock,
  ChevronUp as IconUp,
  EyeOff as IconVisibility,
  Wifi as IconWifi,
  WifiOff as IconWifiOff,
  ZoomIn as IconZoomIn,
  ZoomOut as IconZoomOut,
} from 'lucide-vue-next'
