/**
 * SVG string exports for non-Vue contexts.
 * All icons are normalized to 16x16 with stroke-width 1.5 for compact contexts.
 */
import * as lucide from 'lucide-static'

/** Normalize lucide SVG to 16x16 with stroke-width 1.5 */
function normalize(svg: string): string {
  return svg
    .replace('width="24"', 'width="16"')
    .replace('height="24"', 'height="16"')
    .replace('stroke-width="2"', 'stroke-width="1.5"')
}

// Keep custom table icons on lucide's native 24x24 grid. Do not draw at
// 16x16 and scale with <g transform>; that scales the visual stroke weight
// and makes custom icons look heavier than normalized lucide icons.
function tableIcon(body: string): string {
  return `<svg class="lucide lucide-easyink-table" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`
}

function customIcon(name: string, body: string): string {
  return `<svg class="lucide ${name}" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`
}

export const IconAlignBottom = /* @__PURE__ */ normalize(lucide.AlignEndVertical)
export const IconAlignCenter = /* @__PURE__ */ normalize(lucide.AlignCenter)
export const IconAlignCenterH = /* @__PURE__ */ normalize(lucide.AlignCenterHorizontal)
export const IconAlignEnd = /* @__PURE__ */ normalize(lucide.AlignEndHorizontal)
export const IconAlignLeft = /* @__PURE__ */ normalize(lucide.AlignLeft)
export const IconAlignMiddle = /* @__PURE__ */ normalize(lucide.AlignCenterVertical)
export const IconAlignRight = /* @__PURE__ */ normalize(lucide.AlignRight)
export const IconAlignStart = /* @__PURE__ */ normalize(lucide.AlignStartHorizontal)
export const IconAlignTop = /* @__PURE__ */ normalize(lucide.AlignStartVertical)
export const IconBarcode = /* @__PURE__ */ normalize(lucide.Barcode)
export const IconBold = /* @__PURE__ */ normalize(lucide.Bold)
export const IconBot = /* @__PURE__ */ normalize(lucide.Bot)
export const IconBug = /* @__PURE__ */ normalize(lucide.Bug)
export const IconChartBar = /* @__PURE__ */ normalize(lucide.ChartColumn)
export const IconChart = /* @__PURE__ */ normalize(lucide.BarChart3)
export const IconChartGauge = /* @__PURE__ */ normalize(lucide.Gauge)
export const IconChartLine = /* @__PURE__ */ normalize(lucide.ChartLine)
export const IconChartCustom = /* @__PURE__ */ normalize(lucide.ChartNoAxesCombined)
export const IconChartPie = /* @__PURE__ */ normalize(lucide.ChartPie)
export const IconChartRadar = /* @__PURE__ */ normalize(lucide.Radar)
export const IconChartScatter = /* @__PURE__ */ normalize(lucide.ChartScatter)
export const IconCheck = /* @__PURE__ */ normalize(lucide.Check)
export const IconChevronLeft = /* @__PURE__ */ normalize(lucide.ChevronLeft)
export const IconChevronRight = /* @__PURE__ */ normalize(lucide.ChevronRight)
export const IconCircleAlert = /* @__PURE__ */ normalize(lucide.CircleAlert)
export const IconCircleDot = /* @__PURE__ */ normalize(lucide.CircleDot)
export const IconClear = /* @__PURE__ */ normalize(lucide.Eraser)
export const IconClose = /* @__PURE__ */ normalize(lucide.X)
export const IconCollapse = /* @__PURE__ */ normalize(lucide.ChevronsUpDown)
export const IconCopy = /* @__PURE__ */ normalize(lucide.Copy)
export const IconCopyPlus = /* @__PURE__ */ normalize(lucide.CopyPlus)
export const IconDatabase = /* @__PURE__ */ normalize(lucide.Database)
export const IconDelete = /* @__PURE__ */ normalize(lucide.Trash2)
export const IconDistribute = /* @__PURE__ */ normalize(lucide.AlignHorizontalSpaceBetween)
export const IconDivider = /* @__PURE__ */ normalize(lucide.SeparatorVertical)
export const IconDown = /* @__PURE__ */ normalize(lucide.ChevronDown)
export const IconEllipse = /* @__PURE__ */ normalize(lucide.Circle)
export const IconExpand = /* @__PURE__ */ normalize(lucide.ChevronsRightLeft)
export const IconExport = /* @__PURE__ */ normalize(lucide.Download)
export const IconImport = /* @__PURE__ */ normalize(lucide.Upload)
export const IconFileCheck = /* @__PURE__ */ normalize(lucide.FileCheck)
export const IconFilePen = /* @__PURE__ */ normalize(lucide.FilePen)
export const IconFileText = /* @__PURE__ */ normalize(lucide.FileText)
export const IconFolderClosed = /* @__PURE__ */ normalize(lucide.FolderClosed)
export const IconFolderOpen = /* @__PURE__ */ normalize(lucide.FolderOpen)
export const IconGrid = /* @__PURE__ */ normalize(lucide.Grid3x3)
export const IconGripVertical = /* @__PURE__ */ normalize(lucide.GripVertical)
export const IconGroup = /* @__PURE__ */ normalize(lucide.Group)
export const IconHash = /* @__PURE__ */ normalize(lucide.Hash)
export const IconHidden = /* @__PURE__ */ normalize(lucide.EyeOff)
export const IconHistory = /* @__PURE__ */ normalize(lucide.History)
export const IconImage = /* @__PURE__ */ normalize(lucide.Image)
export const IconItalic = /* @__PURE__ */ normalize(lucide.Italic)
export const IconLayerBottom = /* @__PURE__ */ normalize(lucide.ArrowDownToLine)
export const IconLayerDown = /* @__PURE__ */ normalize(lucide.ArrowDown)
export const IconLayerTop = /* @__PURE__ */ normalize(lucide.ArrowUpToLine)
export const IconLayerUp = /* @__PURE__ */ normalize(lucide.ArrowUp)
export const IconLine = /* @__PURE__ */ normalize(lucide.Minus)
export const IconListTree = /* @__PURE__ */ normalize(lucide.ListTree)
export const IconLoader = /* @__PURE__ */ normalize(lucide.Loader)
export const IconLock = /* @__PURE__ */ normalize(lucide.Lock)
export const IconManager = /* @__PURE__ */ normalize(lucide.Settings)
export const IconMap = /* @__PURE__ */ normalize(lucide.Map)
export const IconMaximize = /* @__PURE__ */ normalize(lucide.Maximize2)
export const IconMessageSquare = /* @__PURE__ */ normalize(lucide.MessageSquare)
export const IconMinimize = /* @__PURE__ */ normalize(lucide.Minus)
export const IconMonitor = /* @__PURE__ */ normalize(lucide.Monitor)
export const IconNewTemplate = /* @__PURE__ */ normalize(lucide.FilePlus)
export const IconPanelLeft = /* @__PURE__ */ normalize(lucide.PanelLeft)
export const IconPanelMaterials = /* @__PURE__ */ normalize(lucide.Blocks)
export const IconPaste = /* @__PURE__ */ normalize(lucide.ClipboardPaste)
export const IconPlus = /* @__PURE__ */ normalize(lucide.Plus)
export const IconPreview = /* @__PURE__ */ normalize(lucide.Eye)
export const IconPrint = /* @__PURE__ */ normalize(lucide.Printer)
export const IconQrcode = /* @__PURE__ */ normalize(lucide.QrCode)
export const IconRect = /* @__PURE__ */ normalize(lucide.Square)
export const IconRedo = /* @__PURE__ */ normalize(lucide.Redo2)
export const IconRingProgress = /* @__PURE__ */ customIcon('lucide-easyink-ring-progress', '<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4.5"/>')
export const IconProgress = /* @__PURE__ */ customIcon('lucide-easyink-progress', '<rect width="18" height="6" x="3" y="9" rx="3"/><path d="M6 12h7"/>')
export const IconRating = /* @__PURE__ */ customIcon('lucide-easyink-rating', '<path d="m6 4 1.1 2.2 2.4.4-1.7 1.7.4 2.4L6 9.6l-2.2 1.1.4-2.4-1.7-1.7 2.4-.4L6 4Z"/><path d="m15 4 .8 1.6 1.7.3-1.2 1.2.3 1.7L15 8l-1.6.8.3-1.7-1.2-1.2 1.7-.3L15 4Z"/><path d="M4 16h16"/><path d="M4 20h10"/>')
export const IconSignature = /* @__PURE__ */ customIcon('lucide-easyink-signature', '<path d="M3 16h18"/><path d="M4 13c2.4-4.8 4.5-7.2 6.2-7.2 1.1 0 1.8.8 1.8 2.1 0 2.6-2.3 5.1-4.1 5.1-.8 0-1.1-.5-.8-1.2.6-1.5 2.9-2 4.5-.8 1.4 1 2.5 2 4.1 2 1.2 0 2.4-.5 4.3-1.8"/>')
export const IconPageNumber = /* @__PURE__ */ normalize(lucide.BookOpen)
export const IconRestoreDefault = /* @__PURE__ */ normalize(lucide.RotateCcw)
export const IconRotation = /* @__PURE__ */ normalize(lucide.RotateCw)
export const IconRuler = /* @__PURE__ */ normalize(lucide.Ruler)
export const IconSave = /* @__PURE__ */ normalize(lucide.Save)
export const IconScissors = /* @__PURE__ */ normalize(lucide.Scissors)
export const IconSearch = /* @__PURE__ */ normalize(lucide.Search)
export const IconSelectAll = /* @__PURE__ */ normalize(lucide.SquareDashedMousePointer)
export const IconSelectSameType = /* @__PURE__ */ normalize(lucide.BoxSelect)
export const IconSliders = /* @__PURE__ */ normalize(lucide.SlidersHorizontal)
export const IconSnap = /* @__PURE__ */ normalize(lucide.Magnet)
export const IconSvg = /* @__PURE__ */ normalize(lucide.FileCode)
export const IconTable = /* @__PURE__ */ normalize(lucide.Table)
export const IconTableInsertColLeft = /* @__PURE__ */ tableIcon('<rect width="12" height="18" x="9" y="3" rx="2"/><path d="M15 3v18"/><path d="M9 9h12"/><path d="M9 15h12"/><path d="M5 9v6"/><path d="M2 12h6"/>')
export const IconTableInsertColRight = /* @__PURE__ */ tableIcon('<rect width="12" height="18" x="3" y="3" rx="2"/><path d="M9 3v18"/><path d="M3 9h12"/><path d="M3 15h12"/><path d="M19 9v6"/><path d="M16 12h6"/>')
export const IconTableInsertRowAbove = /* @__PURE__ */ tableIcon('<rect width="18" height="12" x="3" y="9" rx="2"/><path d="M3 15h18"/><path d="M9 9v12"/><path d="M15 9v12"/><path d="M9 5h6"/><path d="M12 2v6"/>')
export const IconTableInsertRowBelow = /* @__PURE__ */ tableIcon('<rect width="18" height="12" x="3" y="3" rx="2"/><path d="M3 9h18"/><path d="M9 3v12"/><path d="M15 3v12"/><path d="M9 19h6"/><path d="M12 16v6"/>')
export const IconTableMergeRight = /* @__PURE__ */ tableIcon('<rect width="18" height="14" x="3" y="5" rx="2"/><path d="M12 5v14"/><path d="M3 12h18"/><path d="M8 12h7"/><path d="m12 9 3 3-3 3"/>')
export const IconTableMergeDown = /* @__PURE__ */ tableIcon('<rect width="14" height="18" x="5" y="3" rx="2"/><path d="M5 12h14"/><path d="M12 3v18"/><path d="M12 8v7"/><path d="m9 12 3 3 3-3"/>')
export const IconTableMerge = IconTableMergeRight
export const IconTableRemoveCol = /* @__PURE__ */ tableIcon('<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M9 3v18"/><path d="M15 3v18"/><path d="M3 9h18"/><path d="M3 15h18"/><path d="m10 8 4 8"/><path d="m14 8-4 8"/>')
export const IconTableRemoveRow = /* @__PURE__ */ tableIcon('<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M3 9h18"/><path d="M3 15h18"/><path d="M9 3v18"/><path d="M15 3v18"/><path d="m8 10 8 4"/><path d="m16 10-8 4"/>')
export const IconTableSplit = /* @__PURE__ */ normalize(lucide.TableCellsSplit)
export const IconText = /* @__PURE__ */ normalize(lucide.Type)
export const IconTextAlignCenter = /* @__PURE__ */ normalize(lucide.AlignCenter)
export const IconTextAlignLeft = /* @__PURE__ */ normalize(lucide.AlignLeft)
export const IconTextAlignRight = /* @__PURE__ */ normalize(lucide.AlignRight)
export const IconUnderline = /* @__PURE__ */ normalize(lucide.Underline)
export const IconUndo = /* @__PURE__ */ normalize(lucide.Undo2)
export const IconUngroup = /* @__PURE__ */ normalize(lucide.Ungroup)
export const IconUnlock = /* @__PURE__ */ normalize(lucide.Unlock)
export const IconUp = /* @__PURE__ */ normalize(lucide.ChevronUp)
export const IconVisibility = /* @__PURE__ */ normalize(lucide.EyeOff)
export const IconWifi = /* @__PURE__ */ normalize(lucide.Wifi)
export const IconWifiOff = /* @__PURE__ */ normalize(lucide.WifiOff)
export const IconZoomIn = /* @__PURE__ */ normalize(lucide.ZoomIn)
export const IconZoomOut = /* @__PURE__ */ normalize(lucide.ZoomOut)
