/**
 * SVG string exports for non-Vue contexts.
 * All icons are normalized to 16x16 with stroke-width 1.5 for compact contexts.
 */
import * as lucide from 'lucide-static'

/** Normalize lucide SVG to 16x16 with stroke-width 1.5 */
function normalize(svg: string): string {
  return svg
    .replace('width="24"', 'width="16"')
    .replace('height="24"', 'height="16"')
    .replace('stroke-width="2"', 'stroke-width="1.5"')
}

export const IconAlignBottom = /* @__PURE__ */ normalize(lucide.AlignEndVertical)
export const IconAlignCenter = /* @__PURE__ */ normalize(lucide.AlignCenter)
export const IconAlignCenterH = /* @__PURE__ */ normalize(lucide.AlignCenterHorizontal)
export const IconAlignEnd = /* @__PURE__ */ normalize(lucide.AlignEndHorizontal)
export const IconAlignLeft = /* @__PURE__ */ normalize(lucide.AlignLeft)
export const IconAlignMiddle = /* @__PURE__ */ normalize(lucide.AlignCenterVertical)
export const IconAlignRight = /* @__PURE__ */ normalize(lucide.AlignRight)
export const IconAlignStart = /* @__PURE__ */ normalize(lucide.AlignStartHorizontal)
export const IconAlignTop = /* @__PURE__ */ normalize(lucide.AlignStartVertical)
export const IconBarcode = /* @__PURE__ */ normalize(lucide.Barcode)
export const IconBold = /* @__PURE__ */ normalize(lucide.Bold)
export const IconBug = /* @__PURE__ */ normalize(lucide.Bug)
export const IconChart = /* @__PURE__ */ normalize(lucide.BarChart3)
export const IconCheck = /* @__PURE__ */ normalize(lucide.Check)
export const IconChevronLeft = /* @__PURE__ */ normalize(lucide.ChevronLeft)
export const IconChevronRight = /* @__PURE__ */ normalize(lucide.ChevronRight)
export const IconCircleAlert = /* @__PURE__ */ normalize(lucide.CircleAlert)
export const IconCircleDot = /* @__PURE__ */ normalize(lucide.CircleDot)
export const IconClear = /* @__PURE__ */ normalize(lucide.Eraser)
export const IconClose = /* @__PURE__ */ normalize(lucide.X)
export const IconCollapse = /* @__PURE__ */ normalize(lucide.ChevronsUpDown)
export const IconContainer = /* @__PURE__ */ normalize(lucide.LayoutGrid)
export const IconCopy = /* @__PURE__ */ normalize(lucide.Copy)
export const IconCopyPlus = /* @__PURE__ */ normalize(lucide.CopyPlus)
export const IconDatabase = /* @__PURE__ */ normalize(lucide.Database)
export const IconDelete = /* @__PURE__ */ normalize(lucide.Trash2)
export const IconDistribute = /* @__PURE__ */ normalize(lucide.AlignHorizontalSpaceBetween)
export const IconDivider = /* @__PURE__ */ normalize(lucide.SeparatorVertical)
export const IconDown = /* @__PURE__ */ normalize(lucide.ChevronDown)
export const IconEllipse = /* @__PURE__ */ normalize(lucide.Circle)
export const IconExpand = /* @__PURE__ */ normalize(lucide.ChevronsRightLeft)
export const IconExport = /* @__PURE__ */ normalize(lucide.Download)
export const IconFileCheck = /* @__PURE__ */ normalize(lucide.FileCheck)
export const IconFilePen = /* @__PURE__ */ normalize(lucide.FilePen)
export const IconFileText = /* @__PURE__ */ normalize(lucide.FileText)
export const IconFolderClosed = /* @__PURE__ */ normalize(lucide.FolderClosed)
export const IconFolderOpen = /* @__PURE__ */ normalize(lucide.FolderOpen)
export const IconGrid = /* @__PURE__ */ normalize(lucide.Grid3x3)
export const IconGripVertical = /* @__PURE__ */ normalize(lucide.GripVertical)
export const IconGroup = /* @__PURE__ */ normalize(lucide.Group)
export const IconHash = /* @__PURE__ */ normalize(lucide.Hash)
export const IconHidden = /* @__PURE__ */ normalize(lucide.EyeOff)
export const IconHistory = /* @__PURE__ */ normalize(lucide.History)
export const IconImage = /* @__PURE__ */ normalize(lucide.Image)
export const IconItalic = /* @__PURE__ */ normalize(lucide.Italic)
export const IconLayerBottom = /* @__PURE__ */ normalize(lucide.ArrowDownToLine)
export const IconLayerDown = /* @__PURE__ */ normalize(lucide.ArrowDown)
export const IconLayerTop = /* @__PURE__ */ normalize(lucide.ArrowUpToLine)
export const IconLayerUp = /* @__PURE__ */ normalize(lucide.ArrowUp)
export const IconLine = /* @__PURE__ */ normalize(lucide.Minus)
export const IconListTree = /* @__PURE__ */ normalize(lucide.ListTree)
export const IconLoader = /* @__PURE__ */ normalize(lucide.Loader)
export const IconLock = /* @__PURE__ */ normalize(lucide.Lock)
export const IconManager = /* @__PURE__ */ normalize(lucide.Settings)
export const IconMap = /* @__PURE__ */ normalize(lucide.Map)
export const IconMaximize = /* @__PURE__ */ normalize(lucide.Maximize2)
export const IconMessageSquare = /* @__PURE__ */ normalize(lucide.MessageSquare)
export const IconMinimize = /* @__PURE__ */ normalize(lucide.Minus)
export const IconMonitor = /* @__PURE__ */ normalize(lucide.Monitor)
export const IconNewTemplate = /* @__PURE__ */ normalize(lucide.FilePlus)
export const IconPanelLeft = /* @__PURE__ */ normalize(lucide.PanelLeft)
export const IconPanelMaterials = /* @__PURE__ */ normalize(lucide.Blocks)
export const IconPaste = /* @__PURE__ */ normalize(lucide.ClipboardPaste)
export const IconPlus = /* @__PURE__ */ normalize(lucide.Plus)
export const IconPreview = /* @__PURE__ */ normalize(lucide.Eye)
export const IconPrint = /* @__PURE__ */ normalize(lucide.Printer)
export const IconQrcode = /* @__PURE__ */ normalize(lucide.QrCode)
export const IconRect = /* @__PURE__ */ normalize(lucide.Square)
export const IconRedo = /* @__PURE__ */ normalize(lucide.Redo2)
export const IconRelation = /* @__PURE__ */ normalize(lucide.Network)
export const IconRestoreDefault = /* @__PURE__ */ normalize(lucide.RotateCcw)
export const IconRotation = /* @__PURE__ */ normalize(lucide.RotateCw)
export const IconRuler = /* @__PURE__ */ normalize(lucide.Ruler)
export const IconSave = /* @__PURE__ */ normalize(lucide.Save)
export const IconScissors = /* @__PURE__ */ normalize(lucide.Scissors)
export const IconSelectAll = /* @__PURE__ */ normalize(lucide.SquareDashedMousePointer)
export const IconSelectSameType = /* @__PURE__ */ normalize(lucide.BoxSelect)
export const IconSliders = /* @__PURE__ */ normalize(lucide.SlidersHorizontal)
export const IconSnap = /* @__PURE__ */ normalize(lucide.Magnet)
export const IconSvg = /* @__PURE__ */ normalize(lucide.FileCode)
export const IconTable = /* @__PURE__ */ normalize(lucide.Table)
export const IconTableInsertColLeft = /* @__PURE__ */ normalize(lucide.BetweenVerticalStart)
export const IconTableInsertColRight = /* @__PURE__ */ normalize(lucide.BetweenVerticalEnd)
export const IconTableInsertRowAbove = /* @__PURE__ */ normalize(lucide.BetweenHorizontalStart)
export const IconTableInsertRowBelow = /* @__PURE__ */ normalize(lucide.BetweenHorizontalEnd)
export const IconTableMerge = /* @__PURE__ */ normalize(lucide.TableCellsMerge)
export const IconTableRemoveCol = /* @__PURE__ */ normalize(lucide.TableColumnsSplit)
export const IconTableRemoveRow = /* @__PURE__ */ normalize(lucide.TableRowsSplit)
export const IconTableSplit = /* @__PURE__ */ normalize(lucide.TableCellsSplit)
export const IconText = /* @__PURE__ */ normalize(lucide.Type)
export const IconTextAlignCenter = /* @__PURE__ */ normalize(lucide.AlignCenter)
export const IconTextAlignLeft = /* @__PURE__ */ normalize(lucide.AlignLeft)
export const IconTextAlignRight = /* @__PURE__ */ normalize(lucide.AlignRight)
export const IconUnderline = /* @__PURE__ */ normalize(lucide.Underline)
export const IconUndo = /* @__PURE__ */ normalize(lucide.Undo2)
export const IconUngroup = /* @__PURE__ */ normalize(lucide.Ungroup)
export const IconUnlock = /* @__PURE__ */ normalize(lucide.Unlock)
export const IconUp = /* @__PURE__ */ normalize(lucide.ChevronUp)
export const IconVisibility = /* @__PURE__ */ normalize(lucide.EyeOff)
export const IconWifi = /* @__PURE__ */ normalize(lucide.Wifi)
export const IconWifiOff = /* @__PURE__ */ normalize(lucide.WifiOff)
export const IconZoomIn = /* @__PURE__ */ normalize(lucide.ZoomIn)
export const IconZoomOut = /* @__PURE__ */ normalize(lucide.ZoomOut)
