import '@easyink/ui/index.css'

export { default as EasyInkDesigner } from './components/EasyInkDesigner.vue'
export { provideDesignerStore, useDesignerStore, useWorkbenchPersistence } from './composables'
export { registerBuiltinMaterials } from './materials/registry'
export { DesignerStore } from './store/designer-store'
export { createLocalStoragePreferenceProvider } from './store/preference-persistence'
export type { PersistableWorkbenchState } from './store/preference-persistence'
export { createDefaultSaveBranchMenu, createDefaultWorkbenchState } from './store/workbench'
export type * from './types'
