using System;
using System.Globalization;
using System.Text;

namespace EasyInk.Engine.Services;

/// <summary>
/// 在内存中生成测试页 PDF（无外部依赖）。
/// 使用 PDF 内置 Helvetica 字体，生成单页测试文档。
/// </summary>
internal static class TestPageGenerator
{
    private const float A4WidthPt = 595.28f;   // 210mm
    private const float A4HeightPt = 841.89f;  // 297mm
    private const float MarginPt = 36f;        // ~12.7mm
    private const float LineHeight = 14f;

    /// <summary>
    /// 生成快速测试页 PDF（一行文字 + 时间戳）
    /// </summary>
    internal static byte[] GenerateQuick(string printerName, string printPath)
    {
        var sb = new StringBuilder();
        float y = A4HeightPt - MarginPt;

        AppendLine(sb, ref y, 18f, "EasyInk Print Test");
        y -= 8f;
        AppendLine(sb, ref y, 10f, $"Printer: {printerName}");
        AppendLine(sb, ref y, 10f, $"Path: {printPath}");
        AppendLine(sb, ref y, 10f, $"Time: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        y -= 12f;
        AppendLine(sb, ref y, 12f, "ABCDEFGHIJKLMNOPQRSTUVWXYZ");
        AppendLine(sb, ref y, 12f, "abcdefghijklmnopqrstuvwxyz");
        AppendLine(sb, ref y, 12f, "0123456789 !@#$%^&*()");

        return BuildPdf(sb, y);
    }

    /// <summary>
    /// 生成完整诊断测试页 PDF
    /// </summary>
    internal static byte[] GenerateFull(string printerName, string printPath,
        bool statusReady, string? statusDetail, string? paperSize)
    {
        var sb = new StringBuilder();
        float y = A4HeightPt - MarginPt;

        // Header
        AppendLine(sb, ref y, 20f, "EasyInk Print Test Page");
        y -= 4f;
        AppendHorizontalLine(sb, ref y);
        y -= 6f;

        // Printer info
        AppendLine(sb, ref y, 11f, "Printer Information");
        y -= 2f;
        AppendLine(sb, ref y, 10f, $"  Name: {printerName}");
        AppendLine(sb, ref y, 10f, $"  Print Path: {printPath}");
        AppendLine(sb, ref y, 10f, $"  Status Ready: {(statusReady ? "Yes" : "No")}");
        if (!string.IsNullOrEmpty(statusDetail))
            AppendLine(sb, ref y, 10f, $"  Status Detail: {statusDetail}");
        if (!string.IsNullOrEmpty(paperSize))
            AppendLine(sb, ref y, 10f, $"  Paper Size: {paperSize}");
        AppendLine(sb, ref y, 10f, $"  Test Time: {DateTime.Now:yyyy-MM-dd HH:mm:ss.fff}");
        y -= 6f;

        // Text quality section
        AppendLine(sb, ref y, 11f, "Text Quality");
        y -= 2f;
        AppendHorizontalLine(sb, ref y);
        y -= 4f;
        AppendLine(sb, ref y, 14f, "ABCDEFGHIJKLMNOPQRSTUVWXYZ");
        AppendLine(sb, ref y, 14f, "abcdefghijklmnopqrstuvwxyz");
        AppendLine(sb, ref y, 14f, "0123456789 !@#$%^&*()");
        AppendLine(sb, ref y, 14f, "The quick brown fox jumps over the lazy dog");
        y -= 4f;
        AppendLine(sb, ref y, 10f, "Small text: ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789");
        AppendLine(sb, ref y, 8f, "Tiny text: ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789");
        y -= 8f;

        // Line quality section
        AppendLine(sb, ref y, 11f, "Line & Alignment");
        y -= 2f;
        AppendHorizontalLine(sb, ref y);
        y -= 4f;

        // Corner alignment marks
        float left = MarginPt;
        float right = A4WidthPt - MarginPt;
        float markLen = 20f;

        // Top-left
        AppendLineSegment(sb, left, y, left + markLen, y);
        AppendLineSegment(sb, left, y, left, y - markLen);
        // Top-right
        AppendLineSegment(sb, right, y, right - markLen, y);
        AppendLineSegment(sb, right, y, right, y - markLen);

        y -= 30f;
        AppendLine(sb, ref y, 10f, "Corner alignment marks above and below");

        // Bottom alignment marks (leave space)
        float bottomMarkY = MarginPt + markLen + 10f;
        AppendLineSegment(sb, left, bottomMarkY, left + markLen, bottomMarkY);
        AppendLineSegment(sb, left, bottomMarkY + markLen, left, bottomMarkY);
        AppendLineSegment(sb, right, bottomMarkY, right - markLen, bottomMarkY);
        AppendLineSegment(sb, right, bottomMarkY + markLen, right, bottomMarkY);

        y -= 10f;

        // Horizontal rules at different thicknesses
        AppendLine(sb, ref y, 9f, "Horizontal rules:");
        AppendThickLine(sb, ref y, 0.5f);
        y -= 2f;
        AppendThickLine(sb, ref y, 1.0f);
        y -= 2f;
        AppendThickLine(sb, ref y, 2.0f);
        y -= 6f;

        // Footer
        AppendHorizontalLine(sb, ref y);
        y -= 4f;
        AppendLine(sb, ref y, 8f, "Generated by EasyInk Printer - Print Test Feature");

        return BuildPdf(sb, y);
    }

    private static void AppendLine(StringBuilder sb, ref float y, float fontSize, string text)
    {
        var escaped = EscapePdfString(text);
        sb.AppendLine($"BT /F1 {fontSize.ToString("F1", CultureInfo.InvariantCulture)} Tf {MarginPt.ToString("F2", CultureInfo.InvariantCulture)} {y.ToString("F2", CultureInfo.InvariantCulture)} Td ({escaped}) Tj ET");
        y -= fontSize + 2f;
    }

    private static void AppendHorizontalLine(StringBuilder sb, ref float y)
    {
        sb.AppendLine($"{MarginPt.ToString("F2", CultureInfo.InvariantCulture)} {y.ToString("F2", CultureInfo.InvariantCulture)} m {(A4WidthPt - MarginPt).ToString("F2", CultureInfo.InvariantCulture)} {y.ToString("F2", CultureInfo.InvariantCulture)} l S");
        y -= 4f;
    }

    private static void AppendThickLine(StringBuilder sb, ref float y, float lineWidth)
    {
        sb.AppendLine($"{lineWidth.ToString("F1", CultureInfo.InvariantCulture)} w {MarginPt.ToString("F2", CultureInfo.InvariantCulture)} {y.ToString("F2", CultureInfo.InvariantCulture)} m {(A4WidthPt - MarginPt).ToString("F2", CultureInfo.InvariantCulture)} {y.ToString("F2", CultureInfo.InvariantCulture)} l S");
        y -= lineWidth + 2f;
    }

    private static void AppendLineSegment(StringBuilder sb, float x1, float y1, float x2, float y2)
    {
        sb.AppendLine($"{x1.ToString("F2", CultureInfo.InvariantCulture)} {y1.ToString("F2", CultureInfo.InvariantCulture)} m {x2.ToString("F2", CultureInfo.InvariantCulture)} {y2.ToString("F2", CultureInfo.InvariantCulture)} l S");
    }

    private static string EscapePdfString(string text)
    {
        return text
            .Replace("\\", "\\\\")
            .Replace("(", "\\(")
            .Replace(")", "\\)");
    }

    private static byte[] BuildPdf(StringBuilder content, float unusedY)
    {
        var contentBytes = Encoding.ASCII.GetBytes(content.ToString());

        var sb = new StringBuilder();
        var offsets = new System.Collections.Generic.List<int>();

        // Header
        sb.Append("%PDF-1.4\n");

        // Object 1: Catalog
        offsets.Add(sb.Length);
        sb.Append("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");

        // Object 2: Pages
        offsets.Add(sb.Length);
        sb.Append("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");

        // Object 3: Page
        offsets.Add(sb.Length);
        var pageObj = $"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {A4WidthPt.ToString("F2", CultureInfo.InvariantCulture)} {A4HeightPt.ToString("F2", CultureInfo.InvariantCulture)}] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n";
        sb.Append(pageObj);

        // Object 4: Content stream
        offsets.Add(sb.Length);
        sb.Append($"4 0 obj\n<< /Length {contentBytes.Length} >>\nstream\n");
        var headerBytes = Encoding.ASCII.GetBytes(sb.ToString());
        sb.Clear();

        var footer = Encoding.ASCII.GetBytes("\nendstream\nendobj\n");
        sb.Append(footer);

        // Object 5: Font
        offsets.Add(sb.Length);
        sb.Append("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n");

        // Cross-reference table
        var xrefOffset = headerBytes.Length + contentBytes.Length + footer.Length +
                         Encoding.ASCII.GetBytes(sb.ToString()).Length;
        var xref = new StringBuilder();
        xref.Append($"xref\n0 6\n");
        xref.Append("0000000000 65535 f \n");
        foreach (var offset in offsets)
            xref.Append($"{offset:D10} 00000 n \n");

        xref.Append("trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n");
        xref.Append($"{xrefOffset}\n%%EOF");

        var xrefBytes = Encoding.ASCII.GetBytes(xref.ToString());
        var middleBytes = Encoding.ASCII.GetBytes(sb.ToString());

        // Combine all parts
        var result = new byte[headerBytes.Length + contentBytes.Length + footer.Length + middleBytes.Length + xrefBytes.Length];
        var pos = 0;
        Buffer.BlockCopy(headerBytes, 0, result, pos, headerBytes.Length);
        pos += headerBytes.Length;
        Buffer.BlockCopy(contentBytes, 0, result, pos, contentBytes.Length);
        pos += contentBytes.Length;
        Buffer.BlockCopy(footer, 0, result, pos, footer.Length);
        pos += footer.Length;
        Buffer.BlockCopy(middleBytes, 0, result, pos, middleBytes.Length);
        pos += middleBytes.Length;
        Buffer.BlockCopy(xrefBytes, 0, result, pos, xrefBytes.Length);

        return result;
    }
}
